# Generated by Django 5.2.3 on 2025-07-04 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(default='Salón de Clases', help_text="Ej: 'Teórica', 'Laboratorio', 'Seminario', 'Salón de Clases'", max_length=50)),
                ('capacidad', models.IntegerField()),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('recursos_especiales', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=200)),
                ('carga_horaria_maxima', models.IntegerField(default=0)),
                ('disponibilidad', models.JSONField(default=dict)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('regimen', models.CharField(blank=True, max_length=50, null=True)),
                ('dedicatoria', models.CharField(blank=True, max_length=50, null=True)),
                ('carrera_principal', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('horas_semanales', models.IntegerField()),
                ('horas_teoricas', models.IntegerField(default=0)),
                ('horarios_de_practicas', models.IntegerField(default=0)),
                ('horario_de_laboratorio', models.IntegerField(default=0)),
                ('tipo_de_materia', models.CharField(default='Obligatoria', max_length=50)),
                ('secciones_disponibles', models.IntegerField(default=1)),
                ('requisitos_de_aula', models.JSONField(blank=True, default=dict, help_text="Ej: {'tipo_aula': 'Laboratorio', 'recursos_minimos': ['Computadoras', 'Proyector']}", null=True)),
                ('profesores_aptos', models.ManyToManyField(blank=True, related_name='materias_aptas', to='core.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Restriccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('PROFESOR_NO_DISPONIBLE', 'Profesor No Disponible'), ('AULA_NO_DISPONIBLE', 'Aula No Disponible'), ('MATERIA_NO_EN_AULA', 'Materia No Puede Usar Aula Específica')], help_text='Define si la restricción aplica a Profesor, Aula, etc.', max_length=50)),
                ('dia', models.CharField(blank=True, choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes')], max_length=3, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('reglas', models.JSONField(blank=True, help_text='Reglas adicionales en formato JSON (opcional)', null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.aula')),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.materia')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes')], max_length=3)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo_clase', models.CharField(blank=True, max_length=50, null=True)),
                ('seccion', models.CharField(default='1', max_length=10)),
                ('periodo_academico', models.CharField(default='2025-2', max_length=20)),
                ('carrera_programa', models.CharField(default='ingeniero en sistemas', max_length=100)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aula')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.materia')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profesor')),
            ],
            options={
                'unique_together': {('dia', 'hora_inicio', 'aula')},
            },
        ),
    ]
