# Generated by Django 5.2.3 on 2025-07-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='carrera_principal',
            field=models.CharField(default='Sin Carrera Definida', max_length=255),
        ),
    ]
