# Generated by Django 5.2.3 on 2025-07-06 02:12

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_materia_carrera_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_version', models.CharField(help_text='Un nombre descriptivo para esta versión del horario.', max_length=255, unique=True)),
                ('fecha_guardado', models.DateTimeField(auto_now_add=True)),
                ('datos_horario_json', models.JSONField(default=dict, help_text='Copia serializada del conjunto de horarios.', validators=[core.models.validate_json_schema])),
            ],
            options={
                'verbose_name_plural': 'Versiones de Horarios',
                'ordering': ['-fecha_guardado'],
            },
        ),
        migrations.AlterModelOptions(
            name='aula',
            options={'verbose_name_plural': 'Aulas'},
        ),
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ['dia', 'hora_inicio'], 'verbose_name_plural': 'Horarios'},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'verbose_name_plural': 'Materias'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name_plural': 'Profesores'},
        ),
        migrations.AlterModelOptions(
            name='restriccion',
            options={'verbose_name_plural': 'Restricciones'},
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='horario',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_asignados', to='core.aula'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_asignados', to='core.materia'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_asignados', to='core.profesor'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='requisitos_de_aula',
            field=models.JSONField(blank=True, default=dict, help_text="Ej: {'tipo_aula': 'Laboratorio', 'recursos_minimos': ['Computadoras', 'Proyector']}", null=True, validators=[core.models.validate_json_schema]),
        ),
        migrations.AlterField(
            model_name='restriccion',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restricciones_definidas', to='core.aula'),
        ),
        migrations.AlterField(
            model_name='restriccion',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restricciones_definidas', to='core.materia'),
        ),
        migrations.AlterField(
            model_name='restriccion',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restricciones_definidas', to='core.profesor'),
        ),
        migrations.AlterField(
            model_name='restriccion',
            name='reglas',
            field=models.JSONField(blank=True, help_text='Reglas adicionales en formato JSON (opcional)', null=True, validators=[core.models.validate_json_schema]),
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('aula', 'dia', 'hora_inicio', 'hora_fin')},
        ),
        migrations.AlterUniqueTogether(
            name='profesor',
            unique_together={('nombre', 'apellido')},
        ),
        migrations.CreateModel(
            name='SolicitudClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_clase', models.CharField(choices=[('Teoría', 'Teoría'), ('Práctica', 'Práctica'), ('Laboratorio', 'Laboratorio')], max_length=50)),
                ('seccion', models.CharField(max_length=10)),
                ('periodo_academico', models.CharField(max_length=20)),
                ('carrera_programa', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Asignada', 'Asignada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('requisitos_aula_sugeridos', models.JSONField(blank=True, default=dict, null=True, validators=[core.models.validate_json_schema])),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_clase', to='core.materia')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_clase', to='core.profesor')),
            ],
            options={
                'verbose_name_plural': 'Solicitudes de Clases',
                'ordering': ['periodo_academico', 'materia__nombre', 'seccion'],
                'unique_together': {('materia', 'profesor', 'tipo_clase', 'seccion', 'periodo_academico', 'carrera_programa')},
            },
        ),
    ]
